stages: [lint]

lint:
  image: python:3.11-slim
  stage: lint
  before_script:
    - pip install --quiet ruff==0.6.8
  script:
    - ruff ./product || true  # non-blocking lint for now
  rules:
    - when: always
